#!/usr/bin/env bash
# Step: access - non-root deploy user + hardened OpenSSH, with lock-out safety net.
register_step access "Deploy user & SSH" "non-root sudo user · key-only auth · hardened sshd"

step_access_config() {
  defcfg DEPLOY_USER "deploy" "Non-root user that owns deployments (created if missing)"
  defcfg DEPLOY_USER_SSH_KEY "root" "Public key for the deploy user: key text, a file path, or 'root' to copy root's authorized_keys"
  defcfg SSH_PORT "22" "SSH port (changing it cuts most bot noise; 22 is fine behind fail2ban)"
  defcfg SSH_DISABLE_PASSWORD_AUTH true "Disable password logins (key-only). Requires a working key."
  defcfg SSH_DISABLE_ROOT_LOGIN true "Disable direct root SSH login (use the deploy user + sudo)"
  defcfg ACCESS_ROLLBACK_MINUTES "15" "Auto-revert SSH/firewall changes after N minutes unless 'vps-wizard confirm' is run (0 = off)"
}

step_access_enabled() { return 0; }

# resolve_pubkeys : prints authorized_keys content for the deploy user
resolve_pubkeys() {
  local src="$DEPLOY_USER_SSH_KEY"
  if [[ "$src" == root ]]; then
    [[ -s /root/.ssh/authorized_keys ]] && grep -Ev '^\s*(#|$)' /root/.ssh/authorized_keys
  elif [[ -f "$src" ]]; then
    grep -Ev '^\s*(#|$)' "$src"
  elif [[ -n "$src" ]]; then
    printf '%s\n' "$src"
  fi
}

step_access_prompt() {
  ui_note "Best practice: log in as a normal user with a key, escalate with sudo, no passwords over SSH."
  ask "Deploy username" "$DEPLOY_USER" valid_username; DEPLOY_USER="$REPLY"
  local existing_root_keys=0
  [[ -s /root/.ssh/authorized_keys ]] && existing_root_keys=$(grep -cEv '^\s*(#|$)' /root/.ssh/authorized_keys || true)
  if (( existing_root_keys > 0 )); then
    ui_info "root has $existing_root_keys authorized key(s); these can be copied to $DEPLOY_USER."
  else
    ui_warn "root has no authorized_keys. You must provide a public key to avoid lock-out."
    [[ "$DEPLOY_USER_SSH_KEY" == root ]] && DEPLOY_USER_SSH_KEY=""
  fi
  while true; do
    ask "Public key for $DEPLOY_USER ('root' = copy root's keys, or paste ssh-ed25519 ..., or a path)" "$DEPLOY_USER_SSH_KEY" valid_ssh_pubkey
    DEPLOY_USER_SSH_KEY="$REPLY"
    if [[ -n "$(resolve_pubkeys)" ]]; then break; fi
    ui_error "No usable key found in '$DEPLOY_USER_SSH_KEY'."
    [[ "$NONINTERACTIVE" == true ]] && die "DEPLOY_USER_SSH_KEY yields no key"
  done
  ask "SSH port" "$SSH_PORT" valid_port; SSH_PORT="$REPLY"
  ask_yn "Disable password authentication (key-only)?" "$SSH_DISABLE_PASSWORD_AUTH" && SSH_DISABLE_PASSWORD_AUTH=true || SSH_DISABLE_PASSWORD_AUTH=false
  ask_yn "Disable root login over SSH?" "$SSH_DISABLE_ROOT_LOGIN" && SSH_DISABLE_ROOT_LOGIN=true || SSH_DISABLE_ROOT_LOGIN=false
  ask "Safety net: auto-revert SSH changes after N minutes unless confirmed (0 = off)" "$ACCESS_ROLLBACK_MINUTES" valid_int; ACCESS_ROLLBACK_MINUTES="$REPLY"
}

step_access_plan() {
  ui_bullet "Create user $DEPLOY_USER (sudo, docker) with $(resolve_pubkeys | wc -l | tr -d ' ') authorized key(s)"
  ui_bullet "sshd: port $SSH_PORT, PasswordAuthentication $(cfg_bool SSH_DISABLE_PASSWORD_AUTH && echo no || echo yes), PermitRootLogin $(cfg_bool SSH_DISABLE_ROOT_LOGIN && echo no || echo prohibit-password), modern ciphers, AllowUsers $DEPLOY_USER"
  (( ACCESS_ROLLBACK_MINUTES > 0 )) && ui_bullet "Arm ${ACCESS_ROLLBACK_MINUTES}-minute auto-rollback (cancel with: vps-wizard confirm)"
  return 0
}

# ---------------------------------------------------------------------------
# Safety net: schedule a rollback of SSH/firewall changes unless confirmed.
# ---------------------------------------------------------------------------
ROLLBACK_SCRIPT="$WIZARD_ETC/rollback-ssh.sh"
ROLLBACK_UNIT="vpsw-rollback-ssh"

safety_arm() {
  local minutes="$1"
  (( minutes > 0 )) || return 0
  local prev_port; prev_port=$(state_get ssh.previous_port); prev_port=${prev_port:-22}
  write_file "$ROLLBACK_SCRIPT" 0700 <<EOF
#!/usr/bin/env bash
# Auto-generated by vps-wizard: reverts SSH hardening if the operator did not
# confirm access within $minutes minutes. Cancel with: vps-wizard confirm
set -u
logger -t vps-wizard "ROLLBACK: restoring SSH access (no confirmation received)"
rm -f /etc/ssh/sshd_config.d/00-vps-wizard.conf
if command -v ufw >/dev/null && ufw status | grep -q 'Status: active'; then
  ufw allow $prev_port/tcp comment 'ssh (rollback)' >/dev/null 2>&1 || true
  ufw allow $SSH_PORT/tcp comment 'ssh (rollback)' >/dev/null 2>&1 || true
fi
systemctl daemon-reload
systemctl restart ssh.socket 2>/dev/null || true
systemctl restart ssh 2>/dev/null || systemctl restart sshd 2>/dev/null || true
echo "rolled back at \$(date -Is)" > "$WIZARD_STATE/ssh.rolled_back"
EOF
  run_quiet systemctl stop "$ROLLBACK_UNIT.timer" "$ROLLBACK_UNIT.service" 2>/dev/null || true
  run systemd-run --on-active="${minutes}m" --unit="$ROLLBACK_UNIT" --description="vps-wizard SSH rollback safety net" "$ROLLBACK_SCRIPT"
  state_set ssh.rollback_armed "$(date -Is)"
  ui_warn "Safety net armed: SSH changes revert in ${minutes} min unless you run: ${C_BOLD}vps-wizard confirm${C_RESET}"
}

safety_confirm() {
  local had=false
  if systemctl list-units --all 2>/dev/null | grep -q "$ROLLBACK_UNIT"; then had=true; fi
  run_quiet systemctl stop "$ROLLBACK_UNIT.timer" 2>/dev/null || true
  run_quiet systemctl stop "$ROLLBACK_UNIT.service" 2>/dev/null || true
  run_quiet systemctl reset-failed "$ROLLBACK_UNIT.timer" "$ROLLBACK_UNIT.service" 2>/dev/null || true
  rm -f "$ROLLBACK_SCRIPT" "$WIZARD_STATE/ssh.rollback_armed" 2>/dev/null || true
  state_set ssh.confirmed "$(date -Is)"
  if [[ "$had" == true ]]; then ui_ok "Access confirmed - rollback timer cancelled."; else ui_ok "Access confirmed (no rollback timer was pending)."; fi
}

safety_pending() { [[ -f "$WIZARD_STATE/ssh.rollback_armed" ]] && systemctl is-active --quiet "$ROLLBACK_UNIT.timer" 2>/dev/null; }

ssh_restart() {
  if [[ "$DRY_RUN" == true ]]; then run systemctl restart ssh; return 0; fi
  if ! sshd -t 2>>"$WIZARD_LOG_FILE"; then
    ui_error "sshd config test failed - removing drop-in and keeping the old config."
    rm -f /etc/ssh/sshd_config.d/00-vps-wizard.conf
    return 1
  fi
  run systemctl daemon-reload
  if systemctl is-active --quiet ssh.socket 2>/dev/null; then
    run systemctl restart ssh.socket
  fi
  # Debian/Ubuntu call the unit "ssh"; some images alias it as "sshd".
  if systemctl cat ssh.service >/dev/null 2>&1; then run systemctl restart ssh
  else run systemctl restart sshd; fi
}

step_access_apply() {
  local keys; keys=$(resolve_pubkeys)
  [[ -n "$keys" ]] || die "No SSH public key available for $DEPLOY_USER - refusing to continue (would lock you out)."

  # --- user -----------------------------------------------------------------
  if id "$DEPLOY_USER" >/dev/null 2>&1; then
    ui_ok "User $DEPLOY_USER exists"
  else
    run useradd --create-home --shell /bin/bash --user-group "$DEPLOY_USER"
    run passwd -l "$DEPLOY_USER"
    ui_ok "Created user $DEPLOY_USER"
  fi
  run usermod -aG sudo "$DEPLOY_USER"
  getent group docker >/dev/null 2>&1 || run groupadd docker
  run usermod -aG docker "$DEPLOY_USER"
  write_file "/etc/sudoers.d/90-$DEPLOY_USER" 0440 <<<"$DEPLOY_USER ALL=(ALL) NOPASSWD:ALL"

  local home; home=$( { getent passwd "$DEPLOY_USER" || true; } | cut -d: -f6); home=${home:-/home/$DEPLOY_USER}
  if [[ "$DRY_RUN" != true ]]; then
    install -d -m 700 -o "$DEPLOY_USER" -g "$DEPLOY_USER" "$home/.ssh"
    # merge keys (idempotent)
    { [[ -f "$home/.ssh/authorized_keys" ]] && cat "$home/.ssh/authorized_keys"; printf '%s\n' "$keys"; } \
      | awk 'NF && !seen[$0]++' >"$home/.ssh/authorized_keys.tmp"
    mv -f "$home/.ssh/authorized_keys.tmp" "$home/.ssh/authorized_keys"
    chmod 600 "$home/.ssh/authorized_keys"; chown -R "$DEPLOY_USER:$DEPLOY_USER" "$home/.ssh"
  else
    ui_cmd "install authorized_keys for $DEPLOY_USER ($(printf '%s\n' "$keys" | wc -l) key(s))"
  fi
  ui_ok "Authorized keys installed for $DEPLOY_USER"

  # --- sshd -----------------------------------------------------------------
  local prev_port; prev_port=$(ssh_current_port)
  state_has ssh.previous_port || state_set ssh.previous_port "$prev_port"

  # If ufw is already active, allow the new port before we move sshd.
  if have ufw && ufw status 2>/dev/null | grep -q 'Status: active'; then
    run ufw allow "$SSH_PORT/tcp" comment 'ssh'
  fi

  local SSH_PERMIT_ROOT SSH_PASSWORD_AUTH SSH_EXTRA_AUTH_METHODS SSH_ALLOW_USERS
  SSH_PERMIT_ROOT=$(cfg_bool SSH_DISABLE_ROOT_LOGIN && echo no || echo prohibit-password)
  SSH_PASSWORD_AUTH=$(cfg_bool SSH_DISABLE_PASSWORD_AUTH && echo no || echo yes)
  SSH_EXTRA_AUTH_METHODS=$(cfg_bool SSH_DISABLE_PASSWORD_AUTH && echo "" || echo " password")
  SSH_ALLOW_USERS="$DEPLOY_USER"
  cfg_bool SSH_DISABLE_ROOT_LOGIN || SSH_ALLOW_USERS="$DEPLOY_USER root"
  export SSH_PORT SSH_PERMIT_ROOT SSH_PASSWORD_AUTH SSH_EXTRA_AUTH_METHODS SSH_ALLOW_USERS

  # Ubuntu cloud images ship 50-cloud-init.conf with PasswordAuthentication yes;
  # our 00- file sorts first and sshd keeps the first value it sees.
  [[ -d /etc/ssh/sshd_config.d ]] || run mkdir -p /etc/ssh/sshd_config.d
  if [[ "$DRY_RUN" != true ]] && ! grep -qE '^\s*Include\s+/etc/ssh/sshd_config.d/\*\.conf' /etc/ssh/sshd_config; then
    run_sh "sed -i '1i Include /etc/ssh/sshd_config.d/*.conf' /etc/ssh/sshd_config"
  fi
  render_template sshd-hardening.conf | write_file /etc/ssh/sshd_config.d/00-vps-wizard.conf 0600
  # Regenerate weak host keys if any, ensure ed25519 exists
  [[ -f /etc/ssh/ssh_host_ed25519_key ]] || run ssh-keygen -q -N '' -t ed25519 -f /etc/ssh/ssh_host_ed25519_key

  safety_arm "$ACCESS_ROLLBACK_MINUTES"
  ssh_restart || die "sshd restart failed; old config kept."
  ui_ok "sshd hardened on port $SSH_PORT"
  step_mark_done access
}

step_access_status() {
  ui_kv "Deploy user" "$(id "$DEPLOY_USER" >/dev/null 2>&1 && echo "$DEPLOY_USER (groups: $(id -Gn "$DEPLOY_USER" | tr ' ' ','))" || echo "missing")"
  ui_kv "SSH port" "$(ssh_current_port)"
  ui_kv "Password auth" "$(sshd -T 2>/dev/null | awk '$1=="passwordauthentication"{print $2}')"
  ui_kv "Root login" "$(sshd -T 2>/dev/null | awk '$1=="permitrootlogin"{print $2}')"
  if safety_pending; then ui_kv "Rollback timer" "${C_YELLOW}PENDING - run 'vps-wizard confirm'${C_RESET}"; fi
  [[ -f "$WIZARD_STATE/ssh.rolled_back" ]] && ui_kv "Rollback" "${C_RED}SSH hardening was rolled back ($(cat "$WIZARD_STATE/ssh.rolled_back"))${C_RESET}"
  return 0
}
